version: "3.6"

services:
    fastapi_service:
        build: src/.
        volumes:
            - ./src:/usr/src/service
        command: uvicorn main:app --host 0.0.0.0 --port=${SERVICE_PORT} --log-level critical
        hostname: fastapi_service
        container_name: fastapi_service
        ports:
            - "6432:8000"
        healthcheck:
            test: ["CMD-SHELL", "curl -v http://fastapi_service:8000/ping || exit 1"]
            timeout: 15s
            interval: 5s
            retries: 400
        logging:
            driver: none

    testsuite:
        build: testsuite/.
        volumes:
            - ./testsuite:/usr/src/testsuite
        command: pytest . -vvv
        depends_on:
            fastapi_service:
                condition: service_healthy
        env_file:
            - .env
